### ISSUE TITLE
unable to make a hosting account

### ISSUE THREAD

**Issue by AgentDeath253** [mahtab2003/MOFH-R#10]
when i try to make an account i get stuck at the page to choose a subdomain

**Comment by mahtab2003** [comment]
what error is it displaying

**Comment by mahtab2003** [comment]
this issue is related to mofh table to fix that you need to go to your `phpmyadmin > {database_name} > {prefix}mofh` and change this username and password column length from 100 to 256 characters. then set api keys again and it will work fine.

**Comment by mahtab2003** [comment]
have you set the api credentials again?

**Comment by AgentDeath253** [comment]
yes i have

**Comment by mahtab2003** [comment]
> yes i have

try once again

**Comment by AgentDeath253** [comment]
il just go back to xera

**Comment by mahtab2003** [comment]
ok
