### ISSUE TITLE
Links dont work

### ISSUE THREAD

**Issue by ismail1234j** [mahtab2003/MOFH-R#12]
If i click a link then the link is broken

for example

<img width="159" alt="image" src="https://user-images.githubusercontent.com/71182102/200916139-182c4e9e-8532-4ecf-a8c4-9ae9dc3b291c.png">

getting an account list link is broken
even during setup i noticed this issue

in order to access the link i have to modify it

eg. http://carbonhost.live/app/index.php/n/site_settings is the correct link but http://carbonhost.live/app/n/site_settings is shown

please fix as is very irratating

**Comment by AgentDeath253** [comment]
looking at your site and im on it right now not all the files are uploaded

**Comment by AgentDeath253** [comment]
![image](https://user-images.githubusercontent.com/82530339/200950327-d546bb9e-b02e-4055-9a83-ecf93627e282.png)

**Comment by ismail1234j** [comment]
oh sorry it seems i messed up some of the installation. I installed it on the wrong domain anyways as i was meant to install it on a subdomain
i will close this issue.
