### ISSUE TITLE
Google Captcha Response issue & problem when there is more than 5 tickets

### ISSUE THREAD

**Issue by FuryCraft** [mahtab2003/MOFH-R#17]
I noticed that by enabling Google Recaptcha, the dashboard pages that require verification of Recpatcha take longer than they should load. Indeed on the login pages no worries the Captcha verification process is done quickly but when it's on the tickets page or others the answer from Google takes time, while the ticket is already registered in the database. I think there is an infinite loop that runs after the Google response which makes the page take time to load (PHP probably stops the infinite loop after a while to avoid a crash)

**Comment by FuryCraft** [comment]
There is also a problem when there are more than 5 tickets. Indeed, when there are more than 5 tickets, it creates an extra page, but this one returns a 404 Error

**Comment by mahtab2003** [comment]
i will check it

**Comment by mahtab2003** [comment]
> There is also a problem when there are more than 5 tickets. Indeed, when there are more than 5 tickets, it creates an extra page, but this one returns a 404 Error

This issue is fixed

**Comment by mahtab2003** [comment]
> 

If you have smtp enabled it will take time for the process to complete that is not a fault of recaptcha

**Comment by FuryCraft** [comment]
I don't use SMTP
