### ISSUE TITLE
[FEATURE REQUEST] Multiple Free Plans 

### ISSUE THREAD

**Issue by chippytech** [mahtab2003/MOFH-R#18]
Can you please add support for multiple free plans with the ability to open or close a plan when signups are full or manually?

**Comment by chippytech** [comment]
Like heliohost.org.

**Comment by chippytech** [comment]
MyOwnFreeHost has support for multiple plans.

**Comment by mahtab2003** [comment]
ok

**Comment by mahtab2003** [comment]
this request cannot be processed at the moment.
