### ISSUE TITLE
Site/installation won't load 

### ISSUE THREAD

**Issue by 4yx** [mahtab2003/MOFH-R#2]
In https://github.com/mahtab2003/MOFH-R/blob/master/app/config/config.php#L26, the base URL has been hardcoded to this:
```php
$config['base_url'] = 'https://localhost/nxvim/';
```
This forces every instance to redirect to localhost/nxvim, thus failing to load the site and the installation process.

---

Sidenote not related to the issue: ``mofh-r.eu.org`` is the URL mentioned by the repository, when it should probably be [nxvim.freeflarum.com](https://nxvim.freeflarum.com/).

**Comment by mahtab2003** [comment]
Fixed
