### ISSUE TITLE
Database Error

### ISSUE THREAD

**Issue by AgentDeath253** [mahtab2003/MOFH-R#6]
I'm getting a database error every time i try to install

**Comment by mahtab2003** [comment]
i don't know everything is working fine for me. This error occurs when query packet size is greater then allowed packet size

**Comment by FuryCraft** [comment]
Maybe it's because you are in offline mode.

**Comment by FuryCraft** [comment]
![image](https://user-images.githubusercontent.com/44116544/199020499-5d692616-7dd8-4fde-b230-d9c0f772743a.png)

**Comment by AgentDeath253** [comment]
i am online

**Comment by AgentDeath253** [comment]
was

**Comment by mahtab2003** [comment]
> was

i installed it on cPanel server and it is working fine.

**Comment by 4yx** [comment]
@AgentDeath253 you may wish to censor some of the details in the screenshot (essentially replace it, as it can be considered a dox and someone could use this to access the account's password).

Other than that, no idea why it's failing. MOFH can't handle it, perhaps?
You could try installing it locally and then transferring the files and importing the database manually.

**Comment by AgentDeath253** [comment]
ill try now

**Comment by AgentDeath253** [comment]
could it be a issue with model/base.php?

**Comment by AgentDeath253** [comment]
nvm i bypassed it

**Comment by AgentDeath253** [comment]
now the question is could i add support users? on a separate account?

**Comment by AgentDeath253** [comment]
![image](https://user-images.githubusercontent.com/82530339/199135233-bd45c964-4195-4233-be53-62e0ce29841a.png)

**Comment by mahtab2003** [comment]
this error is fixed update template, models and controller files

**Comment by mahtab2003** [comment]
> now the question is could i add support users? on a separate account?

yes
