### ISSUE TITLE
[Enhancements] Upgrade / update dependencies

### ISSUE THREAD

**Issue by FuryCraft** [mahtab2003/MOFH-R#7]
Hi you're using CodeIgniter 3 framework, but it's an old version. Maybe try to upgrade to CodeIgniter 4, wich is in my opinion better than CodeIgniter 3 since it's faster and have less security. Or if you want to keep using CodeIgniter 3, you can update your version to 3.1.13 as you're using the 3.1.11 version.
**Benefits of CodeIgniter 4**

- Compatible with PHP 7.3+ (PHP 7 is the version the most used by devs)
- Fast
- Easy to update (you will need to do a rewrite if you want to upgrade but CodeIgniter 4 updates, don't break other CodeIgniter4 projects, not like CodeIgniter3)
- Native support for .env files
- Use of entities
- Autoloading
- Use of namespaces
- Minimal settings

**Comment by FuryCraft** [comment]
CodeIgniter 3 a été développé pour être utilisé en PHP 5.6 mais si il  supporte la version 7. Les performances ne sont pas les mêmes car CodeIgniter 4 a été pensé pour être utilisé sur la version 7. PHP 5.6 est une version avec plein de failles de sécurité, et est de moins en moins proposée par les hébergeurs.

**Comment by FuryCraft** [comment]
With Xammp you can install PHP 7.4 https://www.apachefriends.org/download.html

**Comment by 4yx** [comment]
> With Xammp you can install PHP 7.4 [apachefriends.org/download.html](https://www.apachefriends.org/download.html)

Same on WAMP, although I don't know what @mahtab2003's computer configurations are.

**Comment by mahtab2003** [comment]
> With Xammp you can install PHP 7.4 https://www.apachefriends.org/download.html

I'm using 32 bit processer and xampp no longer support 32 bit pc

**Comment by 4yx** [comment]
> I'm using 32 bit processer and xampp no longer support 32 bit pc

WAMP offers a 32-bit download that has PHP 7.4: https://www.wampserver.com/en/download-wampserver-32bits/

**Comment by mahtab2003** [comment]
> > I'm using 32 bit processer and xampp no longer support 32 bit pc
> 
> WAMP offers a 32-bit download that has PHP 7.4: https://www.wampserver.com/en/download-wampserver-32bits/

let me check, i never used wamp but i will try

**Comment by mahtab2003** [comment]
> > I'm using 32 bit processer and xampp no longer support 32 bit pc
> 
> WAMP offers a 32-bit download that has PHP 7.4: https://www.wampserver.com/en/download-wampserver-32bits/

my computer hangs whenever i start wamp

**Comment by 4yx** [comment]
> > > I'm using 32 bit processer and xampp no longer support 32 bit pc
> > 
> > 
> > WAMP offers a 32-bit download that has PHP 7.4: [wampserver.com/en/download-wampserver-32bits](https://www.wampserver.com/en/download-wampserver-32bits/)
> 
> my computer hangs whenever i start wamp

Oof. I assume you tried to launch it with XAMPP closed, as it's likely the two would conflict.

**Comment by mahtab2003** [comment]
> 

i closed xampp and start wamp but it hangs whenever i open localhost/phpmyadmin

**Comment by 4yx** [comment]
> > 
> 
> i closed xampp and start wamp but it hangs whenever i open localhost/phpmyadmin

Huh, that's strange. Does it do the same for localhost/phpmyadmin4.9.7/  ?

**Comment by 4yx** [comment]
let me know if it does the same or not. sad if it does though, missed opportunity. oh well, nothing you can do about it unless you have a way to access a better PC.

**Comment by mahtab2003** [comment]
> > i closed xampp and start wamp but it hangs whenever i open localhost/phpmyadmin
> 
> Huh, that's strange. Does it do the same for localhost/phpmyadmin4.9.7/ ?

yup for both

**Comment by FuryCraft** [comment]
It's not the best solution but you  can use a host to test MOFH-R, on infinityfree for exemple
