### ISSUE TITLE
Request: Add Support Role

### ISSUE THREAD

**Issue by AwesomePerson2** [mahtab2003/MOFH-R#9]
this would be useful if you only want people to have access to support tickets

**Comment by mahtab2003** [comment]
> this would be useful if you only want people to have access to support tickets

didn't i tell(actually i have not) there is a support role already there. You can set user role by going to `Menu > Administrator > Hosting Clients > {Client You Want To Make A Staff Member` and change user role to support and save. That's it.

**Comment by mahtab2003** [comment]
for more information read this 
https://nxvim.freeflarum.com/d/8-roles-in-mofh-r
